
package com.thinkit.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VirtualCoffeeServiceImplService", targetNamespace = "http://service.thinkit.com/", wsdlLocation = "http://localhost:7779/ws/coffee?wsdl")
public class VirtualCoffeeServiceImplService
    extends Service
{

    private final static URL VIRTUALCOFFEESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIRTUALCOFFEESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName VIRTUALCOFFEESERVICEIMPLSERVICE_QNAME = new QName("http://service.thinkit.com/", "VirtualCoffeeServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7779/ws/coffee?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIRTUALCOFFEESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        VIRTUALCOFFEESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public VirtualCoffeeServiceImplService() {
        super(__getWsdlLocation(), VIRTUALCOFFEESERVICEIMPLSERVICE_QNAME);
    }

    public VirtualCoffeeServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIRTUALCOFFEESERVICEIMPLSERVICE_QNAME, features);
    }

    public VirtualCoffeeServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, VIRTUALCOFFEESERVICEIMPLSERVICE_QNAME);
    }

    public VirtualCoffeeServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIRTUALCOFFEESERVICEIMPLSERVICE_QNAME, features);
    }

    public VirtualCoffeeServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VirtualCoffeeServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VirtualCoffeeService
     */
    @WebEndpoint(name = "VirtualCoffeeServiceImplPort")
    public VirtualCoffeeService getVirtualCoffeeServiceImplPort() {
        return super.getPort(new QName("http://service.thinkit.com/", "VirtualCoffeeServiceImplPort"), VirtualCoffeeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VirtualCoffeeService
     */
    @WebEndpoint(name = "VirtualCoffeeServiceImplPort")
    public VirtualCoffeeService getVirtualCoffeeServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.thinkit.com/", "VirtualCoffeeServiceImplPort"), VirtualCoffeeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIRTUALCOFFEESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw VIRTUALCOFFEESERVICEIMPLSERVICE_EXCEPTION;
        }
        return VIRTUALCOFFEESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
